project:
  type: website

website:
  title: "Your Neighborhood Scientist"
  description: "science news for everyone"
  site-url: https://ynscientist.github.io # TODO change to custom domain
  repo-url: https://github.com/ynscientist/ynscientist.github.io # TODO change to website repo
  favicon: TODO
  open-graph: true
  search:
    location: navbar
    type: textbox
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: rss
        href: index.xml

format:
  html:
    theme: 
      - brand
      - cosmo
    css: styles.css
    embed-resources: true

execute:
  freeze: auto

